title: Meatspace Games
email: f-prettyland@users.noreply.github.com
description: A collection of great minimalist board/card games you can play anywhere with a few objects
baseurl: "/meatspace-games"
url: "https://f-prettyland.github.io"
# twitter_username: jekyllrb
github_username:  f-prettyland

# Build settings
markdown: kramdown
theme: minima
